language: php
dist: trusty
sudo: false

services:
  - mysql

php:
  - 7.2

env:
  global:
    - MYSQL_DATABASE=drupal
    - MYSQL_HOSTNAME=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
  - printenv
  - git checkout $TRAVIS_BRANCH

install:
  - composer --verbose validate
  - composer --verbose install

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush -y sql-create
  - ./../vendor/bin/drush -y site-install --existing-config
  - git checkout -
  - composer install
  - ./../vendor/bin/drush cr
  - ./../vendor/bin/drush -y updb
  - ./../vendor/bin/drush -y cex
  - git diff ../config
